#!/usr/bin/env bash
# Regenerate dcheck/src/oui_table.rs: every IEEE OUI registered to the drive
# makers dcheck knows (see dcheck/src/authenticity.rs).
#
# Usage: scripts/gen-dcheck-oui.sh [oui.txt]
#   oui.txt  IEEE MA-L registry. Default: /usr/share/hwdata/oui.txt (Fedora
#            hwdata) or /usr/share/ieee-data/oui.txt (Debian ieee-data);
#            upstream https://standards-oui.ieee.org/oui/oui.txt
set -euo pipefail

SRC="${1:-}"
if [ -z "$SRC" ]; then
    for f in /usr/share/hwdata/oui.txt /usr/share/ieee-data/oui.txt; do
        [ -f "$f" ] && SRC="$f" && break
    done
fi
[ -n "$SRC" ] && [ -f "$SRC" ] || { echo "usage: $0 path/to/oui.txt" >&2; exit 1; }

OUT="$(cd "$(dirname "$0")/.." && pwd)/dcheck/src/oui_table.rs"
{
    echo "// Generated by scripts/gen-dcheck-oui.sh from the IEEE OUI registry"
    echo "// ($(basename "$SRC"), $(grep -c '(base 16)' "$SRC") entries). Do not edit."
    echo
    echo "/// (OUI, maker) sorted by OUI; makers match \`authenticity::MAKERS\`."
    echo "pub const OUI_MAKERS: &[(&str, &str)] = &["
    tr -d '\r' < "$SRC" | awk '
        / \(base 16\)/ {
            oui = tolower($1); $1 = ""; $2 = ""; $3 = ""; org = $0
            m = ""
            if (org ~ /Samsung Electronics/) m = "Samsung"
            else if (org ~ /Western Digital|HGST|SanDisk|Hitachi Global Storage/) m = "Western Digital"
            else if (org ~ /Seagate/) m = "Seagate"
            else if (org ~ /TOSHIBA|Toshiba|Kioxia|KIOXIA|FUJITSU LIMITED/) m = "Toshiba/Kioxia"
            else if (org ~ /MICRON|Micron Technology/) m = "Micron/Crucial"
            else if (org ~ /Intel Corporat|Solidigm/) m = "Intel/Solidigm"
            else if (org ~ /Kingston Technology/) m = "Kingston"
            else if (org ~ /SK hynix|Hynix/) m = "SK hynix"
            if (m != "") printf "    (\"%s\", \"%s\"),\n", oui, m
        }' | sort -u
    echo "];"
} > "$OUT"
echo "wrote $OUT ($(grep -c '^    ("' "$OUT") OUIs)"
